from __future__ import annotations
"""
CrimeVision-QA — Frame Describer QLoRA Fine-Tuning

Fine-tunes Qwen2-VL-7B-Instruct on surveillance frame description pairs
generated by generate_frame_data.py.

After training, set USE_LOCAL_VLM=true in .env and point
LOCAL_VLM_ADAPTER_PATH to the checkpoint to replace kimi-k2p5 API calls.

REQUIRES GPU — Google Colab A100 (40 GB) recommended.
Estimated time on A100: ~1.5–2.5 hours for 100–200 image pairs, 3 epochs.

Usage:
    python finetune/train_frame_describer.py \
        --data finetune/data/frame_training_data.json \
        --output finetune/output/frame_describer \
        --epochs 3

Dependencies (install on GPU machine):
    pip install torch transformers peft trl bitsandbytes datasets accelerate qwen-vl-utils
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


def _ensure_utf8_mode() -> None:
    if os.name != "nt":
        return
    if sys.flags.utf8_mode:
        return
    env = os.environ.copy()
    env["PYTHONUTF8"] = "1"
    result = subprocess.run([sys.executable, "-X", "utf8", *sys.argv], env=env)
    raise SystemExit(result.returncode)


def _check_deps():
    missing = []
    for pkg in ["torch", "transformers", "peft", "trl", "bitsandbytes", "datasets", "qwen_vl_utils"]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if missing:
        print(f"[VLM-FT] Missing dependencies: {', '.join(missing)}")
        print("Install: pip install torch transformers peft trl bitsandbytes datasets accelerate qwen-vl-utils")
        sys.exit(1)


BASE_MODEL = os.getenv("FRAME_BASE_MODEL", "Qwen/Qwen2-VL-2B-Instruct")
LORA_RANK = 16
LORA_ALPHA = 32
# Target the language decoder layers — vision encoder kept frozen to save VRAM
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
LEARNING_RATE = 1e-4
MAX_SEQ_LEN = 1024


def _build_messages(example: dict) -> list[dict]:
    """Build Qwen2-VL chat-format messages from one training example."""
    return [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": example["image_path"]},
                {"type": "text",  "text": example["instruction"]},
            ],
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": example["description"]}],
        },
    ]


def train(data_path: str, output_dir: str, epochs: int, batch_size: int) -> None:
    _ensure_utf8_mode()
    _check_deps()

    import torch
    from datasets import Dataset
    from transformers import AutoProcessor, BitsAndBytesConfig
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    from qwen_vl_utils import process_vision_info

    # Qwen2-VL uses its own model class
    from transformers import Qwen2VLForConditionalGeneration

    with open(data_path) as f:
        raw_data = json.load(f)

    if not raw_data:
        print(f"[VLM-FT] No training examples in {data_path}. Run generate_frame_data.py first.")
        sys.exit(1)

    print(f"[VLM-FT] Loaded {len(raw_data)} training examples")

    use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    compute_dtype = torch.bfloat16 if use_bf16 else torch.float16

    # 4-bit quantization to fit 7B model in A100 40GB with room for gradients
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
    )

    print(f"[VLM-FT] Loading base model: {BASE_MODEL}")
    processor = AutoProcessor.from_pretrained(BASE_MODEL, trust_remote_code=True)

    model = Qwen2VLForConditionalGeneration.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=LORA_RANK,
        lora_alpha=LORA_ALPHA,
        target_modules=LORA_TARGET_MODULES,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    skipped_too_long = 0

    def tokenise(example: dict):
        nonlocal skipped_too_long
        messages = _build_messages(example)
        text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=False,
            return_tensors="pt",
        )
        # Labels = input_ids with prompt tokens masked (-100)
        input_ids = inputs["input_ids"][0]
        if input_ids.shape[0] > MAX_SEQ_LEN:
            skipped_too_long += 1
            return None
        labels = input_ids.clone()
        # Mask everything up to and including the last <|im_start|>assistant token
        assistant_token = processor.tokenizer.encode("<|im_start|>assistant", add_special_tokens=False)
        for i in range(len(input_ids) - len(assistant_token)):
            if input_ids[i : i + len(assistant_token)].tolist() == assistant_token:
                labels[: i + len(assistant_token)] = -100
                break
        return {
            "input_ids":      input_ids,
            "attention_mask": inputs["attention_mask"][0],
            "mm_token_type_ids": inputs["mm_token_type_ids"][0],
            "pixel_values":   inputs.get("pixel_values"),
            "image_grid_thw": inputs.get("image_grid_thw"),
            "labels":         labels,
        }

    print("[VLM-FT] Tokenising dataset...")
    tokenised = [item for ex in raw_data if (item := tokenise(ex)) is not None]
    if not tokenised:
        print(f"[VLM-FT] No usable tokenised examples remain under max length {MAX_SEQ_LEN}.")
        sys.exit(1)
    if skipped_too_long:
        print(f"[VLM-FT] Skipped {skipped_too_long} examples longer than {MAX_SEQ_LEN} tokens")

    # Custom collator to handle variable-length pixel_values
    def collate_fn(batch):
        import torch
        from torch.nn.utils.rnn import pad_sequence

        input_ids = pad_sequence(
            [b["input_ids"] for b in batch], batch_first=True,
            padding_value=processor.tokenizer.pad_token_id
        )
        attention_mask = pad_sequence(
            [b["attention_mask"] for b in batch], batch_first=True, padding_value=0
        )
        mm_token_type_ids = pad_sequence(
            [b["mm_token_type_ids"] for b in batch], batch_first=True, padding_value=0
        )
        labels = pad_sequence(
            [b["labels"] for b in batch], batch_first=True, padding_value=-100
        )
        result = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "mm_token_type_ids": mm_token_type_ids,
            "labels": labels,
        }
        pv = [b["pixel_values"] for b in batch if b["pixel_values"] is not None]
        if pv:
            result["pixel_values"] = torch.cat(pv, dim=0)
        image_grid = [b["image_grid_thw"] for b in batch if b["image_grid_thw"] is not None]
        if image_grid:
            result["image_grid_thw"] = torch.cat(image_grid, dim=0)
        return result

    from torch.utils.data import DataLoader
    from transformers import get_cosine_schedule_with_warmup
    from torch.optim import AdamW

    loader = DataLoader(tokenised, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
    total_steps = len(loader) * epochs
    optimizer = AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=0.01)
    scheduler = get_cosine_schedule_with_warmup(
        optimizer, num_warmup_steps=max(1, int(total_steps * 0.05)), num_training_steps=total_steps
    )

    model.train()
    global_step = 0
    print(f"[VLM-FT] Starting training: {epochs} epochs, {len(loader)} steps/epoch")

    for epoch in range(1, epochs + 1):
        total_loss = 0.0
        for batch in loader:
            batch = {k: v.to(model.device) if hasattr(v, "to") else v for k, v in batch.items()}
            outputs = model(**batch)
            loss = outputs.loss
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()
            total_loss += loss.item()
            global_step += 1
            if global_step % 10 == 0:
                print(f"  step {global_step}/{total_steps}  loss={loss.item():.4f}")

        avg_loss = total_loss / len(loader)
        print(f"[VLM-FT] Epoch {epoch}/{epochs}  avg_loss={avg_loss:.4f}")

        # Save checkpoint per epoch
        epoch_dir = os.path.join(output_dir, f"checkpoint-epoch-{epoch}")
        model.save_pretrained(epoch_dir)
        processor.save_pretrained(epoch_dir)
        print(f"[VLM-FT] Checkpoint saved → {epoch_dir}")

    # Save final adapter
    final_path = os.path.join(output_dir, "checkpoint-final")
    model.save_pretrained(final_path)
    processor.save_pretrained(final_path)
    print(f"[VLM-FT] Final adapter saved → {final_path}")
    print(f"[VLM-FT] Set LOCAL_VLM_ADAPTER_PATH={final_path} in .env to use this model")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="finetune/data/frame_training_data.json")
    parser.add_argument("--output", default="finetune/output/frame_describer")
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=1,
                        help="Per-device batch size (default 1 — images are large; use grad accumulation)")
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)
    train(args.data, args.output, args.epochs, args.batch_size)


if __name__ == "__main__":
    main()
